# Generated by Django 2.1.7 on 2019-06-18 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('img', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
